// Code generated by ent, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/jdhenke/bug-3208/ent/runtime.go

const (
	Version = "v0.11.5-0.20230102205927-542f36d4abda"           // Version of ent codegen.
	Sum     = "h1:sZuDPH3IYaAE4LG7bovoBuYaT7HKSz1vknnVjwm2PVA=" // Sum of ent codegen.
)
