// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"

	entfield "github.com/jdhenke/bug-3208/ent/field"
)

// Field is the model entity for the Field schema.
type Field struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Field) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case entfield.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Field", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Field fields.
func (f *Field) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case entfield.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			f.ID = int(value.Int64)
		}
	}
	return nil
}

// Update returns a builder for updating this Field.
// Note that you need to call Field.Unwrap() before calling this method if this Field
// was returned from a transaction, and the transaction was committed or rolled back.
func (f *Field) Update() *FieldUpdateOne {
	return (&FieldClient{config: f.config}).UpdateOne(f)
}

// Unwrap unwraps the Field entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (f *Field) Unwrap() *Field {
	_tx, ok := f.config.driver.(*txDriver)
	if !ok {
		panic("ent: Field is not a transactional entity")
	}
	f.config.driver = _tx.drv
	return f
}

// String implements the fmt.Stringer.
func (f *Field) String() string {
	var builder strings.Builder
	builder.WriteString("Field(")
	builder.WriteString(fmt.Sprintf("id=%v", f.ID))
	builder.WriteByte(')')
	return builder.String()
}

// Fields is a parsable slice of Field.
type Fields []*Field

func (f Fields) config(cfg config) {
	for _i := range f {
		f[_i].config = cfg
	}
}
