// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Field is the predicate function for entfield builders.
type Field func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
